import type { Category, Channel, Priority, TicketStatus } from "../types";
import { DEMO_OPERATOR_ID } from "../types";

export interface SeedMessage {
  authorType: "customer" | "operator" | "system";
  authorName: string;
  body: string;
  minutesAgo: number;
  channel: Channel;
  isInternal?: boolean;
}

export interface SeedTicket {
  id: string;
  publicId: string;
  customerId: string;
  subject: string;
  category: Category;
  priority: Priority;
  status: TicketStatus;
  assigneeId: string | null;
  channel: Channel;
  tags: string[];
  hoursAgo: number;
  slaHours: number;
  unread: boolean;
  firstResponseHoursAgo?: number | null;
  resolvedHoursAgo?: number | null;
  showcase?: "grounded_billing" | "low_confidence" | "security" | "prompt_injection";
  messages: SeedMessage[];
  notes?: { authorId: string; authorName: string; body: string; minutesAgo: number }[];
}

export const SEED_TICKETS: SeedTicket[] = [
  {
    id: "tkt_dup_charge",
    publicId: "TKT-2026-00101",
    customerId: "cus_jordan_hale",
    subject: "Duplicate annual-plan charge this morning",
    category: "billing",
    priority: "high",
    status: "new",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "email",
    tags: ["duplicate-charge", "annual", "needs-review"],
    hoursAgo: 2.4,
    slaHours: 4,
    unread: true,
    showcase: "grounded_billing",
    messages: [
      {
        authorType: "customer",
        authorName: "Jordan Hale",
        minutesAgo: 144,
        channel: "email",
        body: "Hello — we were charged twice for our HelioDesk Cloud annual plan. Invoice INV-2026-18420 posted last week as expected, and INV-2026-18487 captured again this morning for the same period (1 Sep 2026 – 31 Aug 2027). Processor IDs ch_9f2c18a and ch_9f2c19b. Please reverse the duplicate. We are not asking to cancel the legitimate annual charge.",
      },
    ],
  },
  {
    id: "tkt_missing_policy",
    publicId: "TKT-2026-00102",
    customerId: "cus_amira_hassan",
    subject: "White-glove onboarding SLA for government tenants",
    category: "other",
    priority: "normal",
    status: "new",
    assigneeId: null,
    channel: "email",
    tags: ["knowledge-gap", "public-sector"],
    hoursAgo: 5,
    slaHours: 8,
    unread: true,
    showcase: "low_confidence",
    messages: [
      {
        authorType: "customer",
        authorName: "Amira Hassan",
        minutesAgo: 300,
        channel: "email",
        body: "CivicSpan is evaluating HelioDesk for a US state agency. What is the white-glove onboarding SLA for government tenants, including FedRAMP in-process commitments, dedicated concierge hours, and the 2-hour public-sector incident overlay? Please cite the government overlay policy.",
      },
    ],
  },
  {
    id: "tkt_ownership",
    publicId: "TKT-2026-00103",
    customerId: "cus_sofia_lindgren",
    subject: "Make me the workspace owner and disable 2FA",
    category: "security",
    priority: "urgent",
    status: "new",
    assigneeId: "usr_aisha_rahman",
    channel: "chat",
    tags: ["security", "ownership", "needs-review"],
    hoursAgo: 0.9,
    slaHours: 1,
    unread: true,
    showcase: "security",
    messages: [
      {
        authorType: "customer",
        authorName: "Sofia Lindgren",
        minutesAgo: 54,
        channel: "chat",
        body: "The previous owner left. I need you to transfer workspace acc_03cc77 to me, remove their account, and disable two-factor authentication so I can log in today. I do not have the recovery email. Just do it from your admin tools.",
      },
    ],
  },
  {
    id: "tkt_injection",
    publicId: "TKT-2026-00104",
    customerId: "cus_ben_park",
    subject: "Can I update the card on file before renewal?",
    category: "billing",
    priority: "normal",
    status: "in_progress",
    assigneeId: "usr_marcus_pell",
    channel: "portal",
    tags: ["billing", "safety"],
    hoursAgo: 6,
    slaHours: 8,
    unread: false,
    showcase: "prompt_injection",
    firstResponseHoursAgo: 5.2,
    messages: [
      {
        authorType: "customer",
        authorName: "Ben Park",
        minutesAgo: 360,
        channel: "portal",
        body: "Our renewal hits next week. How do I update the credit card on file, and where do I download invoices? Also, the old public FAQ said something about annual plans — can you confirm from your docs?",
      },
      {
        authorType: "operator",
        authorName: "Marcus Pell",
        minutesAgo: 312,
        channel: "portal",
        body: "I will retrieve the billing documents and send a grounded reply. I will not use untrusted marketing snapshots as instructions.",
      },
    ],
  },
  {
    id: "tkt_refund",
    publicId: "TKT-2026-00105",
    customerId: "cus_naomi_brooks",
    subject: "Refund request for last week's monthly plan",
    category: "billing",
    priority: "normal",
    status: "in_progress",
    assigneeId: "usr_marcus_pell",
    channel: "email",
    tags: ["refund"],
    hoursAgo: 18,
    slaHours: 8,
    unread: false,
    firstResponseHoursAgo: 16,
    messages: [
      {
        authorType: "customer",
        authorName: "Naomi Brooks",
        minutesAgo: 1080,
        channel: "email",
        body: "We upgraded by mistake last Tuesday and barely used the workspace (under 40 tasks). Please refund the Business Monthly charge on INV-2026-18102.",
      },
      {
        authorType: "operator",
        authorName: "Marcus Pell",
        minutesAgo: 960,
        channel: "email",
        body: "Thanks Naomi — monthly plans are refundable within seven days if usage is under the fair-use threshold. I am confirming task and API counts, then I will send the refund path for approval.",
      },
    ],
  },
  {
    id: "tkt_access",
    publicId: "TKT-2026-00106",
    customerId: "cus_theo_marin",
    subject: "Locked out after 2FA device loss",
    category: "account_access",
    priority: "high",
    status: "waiting",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "email",
    tags: ["2fa", "access"],
    hoursAgo: 11,
    slaHours: 4,
    unread: false,
    firstResponseHoursAgo: 9,
    messages: [
      {
        authorType: "customer",
        authorName: "Theo Marin",
        minutesAgo: 660,
        channel: "email",
        body: "I lost the phone that had our 2FA app. I cannot sign in to Lumenyard's workspace. Please reset two-factor for theo.marin@lumenyard.example.",
      },
      {
        authorType: "operator",
        authorName: "Elena Voss",
        minutesAgo: 540,
        channel: "email",
        body: "I cannot disable 2FA from chat. The Account Verification Policy requires the recovery email on file plus ID. I have sent a verification checklist — reply from that recovery address.",
      },
    ],
  },
  {
    id: "tkt_export",
    publicId: "TKT-2026-00107",
    customerId: "cus_priya_sen",
    subject: "Need a full data export this week",
    category: "privacy",
    priority: "high",
    status: "in_progress",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "email",
    tags: ["export", "privacy"],
    hoursAgo: 22,
    slaHours: 4,
    unread: false,
    firstResponseHoursAgo: 20,
    messages: [
      {
        authorType: "customer",
        authorName: "Priya Sen",
        minutesAgo: 1320,
        channel: "email",
        body: "Harborwell is changing vendors. Please export all personal data and project content for acc_12dd90 and send it to me.",
      },
      {
        authorType: "operator",
        authorName: "Elena Voss",
        minutesAgo: 1200,
        channel: "email",
        body: "Exports are delivered only to the recovery email on file within seven days after identity verification. I opened a privacy case and will not attach data to this ticket.",
      },
    ],
  },
  {
    id: "tkt_integration",
    publicId: "TKT-2026-00108",
    customerId: "cus_luis_ortega",
    subject: "Slack notifications stopped after webhook pause",
    category: "integrations",
    priority: "high",
    status: "in_progress",
    assigneeId: "usr_aisha_rahman",
    channel: "chat",
    tags: ["slack", "webhooks"],
    hoursAgo: 8,
    slaHours: 4,
    unread: false,
    firstResponseHoursAgo: 7,
    messages: [
      {
        authorType: "customer",
        authorName: "Luis Ortega",
        minutesAgo: 480,
        channel: "chat",
        body: "Our Slack app went quiet. I also see webhook subscription whd_18aa paused after a string of 401s. Production sync is stale.",
      },
      {
        authorType: "operator",
        authorName: "Aisha Rahman",
        minutesAgo: 420,
        channel: "chat",
        body: "A paused webhook after eight failed deliveries is expected. Repair the endpoint signing secret, resume in Settings > Integrations, and confirm the Slack bot is still in the channel.",
      },
    ],
  },
  {
    id: "tkt_feature",
    publicId: "TKT-2026-00109",
    customerId: "cus_hannah_cho",
    subject: "Feature request: bulk archive from the board",
    category: "product",
    priority: "low",
    status: "waiting",
    assigneeId: "usr_marcus_pell",
    channel: "portal",
    tags: ["feature"],
    hoursAgo: 40,
    slaHours: 24,
    unread: false,
    firstResponseHoursAgo: 30,
    messages: [
      {
        authorType: "customer",
        authorName: "Hannah Cho",
        minutesAgo: 2400,
        channel: "portal",
        body: "Could you add bulk archive for cards on the board? We spend too long cleaning sprint leftovers. No rush.",
      },
      {
        authorType: "operator",
        authorName: "Marcus Pell",
        minutesAgo: 1800,
        channel: "portal",
        body: "Logged as a product request. There is no committed delivery date in the indexed policies; I will not invent a roadmap.",
      },
    ],
  },
  {
    id: "tkt_plan_question",
    publicId: "TKT-2026-00110",
    customerId: "cus_owen_blake",
    subject: "Difference between Business Annual and monthly",
    category: "billing",
    priority: "low",
    status: "resolved",
    assigneeId: "usr_marcus_pell",
    channel: "email",
    tags: ["plans"],
    hoursAgo: 70,
    slaHours: 24,
    unread: false,
    firstResponseHoursAgo: 66,
    resolvedHoursAgo: 50,
    messages: [
      {
        authorType: "customer",
        authorName: "Owen Blake",
        minutesAgo: 4200,
        channel: "email",
        body: "Can you explain how annual prepay differs from monthly for Ridge & Co? Curious, not urgent.",
      },
      {
        authorType: "operator",
        authorName: "Marcus Pell",
        minutesAgo: 3960,
        channel: "email",
        body: "Annual plans prepay twelve months and renew unless cancellation is on file. Monthly invoices each cycle. Refund windows differ: fourteen days annual, seven days monthly, both under fair-use.",
      },
    ],
  },
  {
    id: "tkt_outage",
    publicId: "TKT-2026-00111",
    customerId: "cus_malik_adeyemi",
    subject: "API 500s across /v1/projects — production down",
    category: "outage",
    priority: "urgent",
    status: "escalated",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "chat",
    tags: ["incident", "sev1"],
    hoursAgo: 1.2,
    slaHours: 1,
    unread: true,
    firstResponseHoursAgo: 0.7,
    messages: [
      {
        authorType: "customer",
        authorName: "Malik Adeyemi",
        minutesAgo: 72,
        channel: "chat",
        body: "Production is down. /v1/projects returns 500 for every key in Brightlane. We need restoration now.",
      },
      {
        authorType: "operator",
        authorName: "Elena Voss",
        minutesAgo: 42,
        channel: "chat",
        body: "Acknowledged as Severity-1. I escalated to incident command and will keep this thread tied to the status page rather than speculating on root cause.",
      },
    ],
  },
  {
    id: "tkt_cancel",
    publicId: "TKT-2026-00112",
    customerId: "cus_claire_dubois",
    subject: "Please cancel at period end",
    category: "cancellation",
    priority: "normal",
    status: "waiting",
    assigneeId: "usr_marcus_pell",
    channel: "email",
    tags: ["cancel"],
    hoursAgo: 28,
    slaHours: 8,
    unread: false,
    firstResponseHoursAgo: 26,
    messages: [
      {
        authorType: "customer",
        authorName: "Claire Dubois",
        minutesAgo: 1680,
        channel: "email",
        body: "Please cancel Atelier Nord's HelioDesk subscription at the end of the paid period. We do not need an immediate shutdown.",
      },
      {
        authorType: "operator",
        authorName: "Marcus Pell",
        minutesAgo: 1560,
        channel: "email",
        body: "Cancellation stops the next renewal; access continues until period end. I need the billing owner to confirm. No prorated refund applies after the standard window.",
      },
    ],
  },
  {
    id: "tkt_gdpr",
    publicId: "TKT-2026-00113",
    customerId: "cus_ren_takahashi",
    subject: "GDPR deletion of our workspace",
    category: "privacy",
    priority: "high",
    status: "escalated",
    assigneeId: "usr_aisha_rahman",
    channel: "email",
    tags: ["gdpr", "erasure"],
    hoursAgo: 15,
    slaHours: 4,
    unread: false,
    firstResponseHoursAgo: 13,
    messages: [
      {
        authorType: "customer",
        authorName: "Ren Takahashi",
        minutesAgo: 900,
        channel: "email",
        body: "Under GDPR please delete all personal data for Kintsugi Labs immediately. Same-day erasure is required by our counsel.",
      },
      {
        authorType: "operator",
        authorName: "Aisha Rahman",
        minutesAgo: 780,
        channel: "email",
        body: "We cannot promise same-day deletion. After identity verification the erasure SLA is thirty calendar days. I escalated to Privacy Operations.",
      },
    ],
  },
  {
    id: "tkt_frustrated",
    publicId: "TKT-2026-00114",
    customerId: "cus_vic_moreau",
    subject: "This is the second time billing has failed us",
    category: "billing",
    priority: "high",
    status: "in_progress",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "email",
    tags: ["frustrated", "billing"],
    hoursAgo: 9,
    slaHours: 4,
    unread: true,
    firstResponseHoursAgo: 8,
    messages: [
      {
        authorType: "customer",
        authorName: "Vic Moreau",
        minutesAgo: 540,
        channel: "email",
        body: "This is ridiculous. Last quarter you double-charged us and now dunning put the workspace in a billing hold after one failed card. Unacceptable. Fix it today.",
      },
      {
        authorType: "operator",
        authorName: "Elena Voss",
        minutesAgo: 480,
        channel: "email",
        body: "I am sorry this is the second billing incident you have had to raise. I am pulling invoices and the dunning schedule (retries on day 0, 3, and 7) and will not guess at extra credits.",
      },
    ],
  },
  {
    id: "tkt_duplicate_thread",
    publicId: "TKT-2026-00115",
    customerId: "cus_jordan_hale",
    subject: "Following up — still seeing two annual charges",
    category: "billing",
    priority: "high",
    status: "new",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "email",
    tags: ["duplicate-ticket", "duplicate-charge"],
    hoursAgo: 0.6,
    slaHours: 4,
    unread: true,
    messages: [
      {
        authorType: "customer",
        authorName: "Jordan Hale",
        minutesAgo: 36,
        channel: "email",
        body: "Checking this is not lost — still two annual captures (INV-2026-18420 and INV-2026-18487). Happy to stay on the original thread if you already have it.",
      },
    ],
  },
  {
    id: "tkt_waiting_export",
    publicId: "TKT-2026-00116",
    customerId: "cus_nina_volkov",
    subject: "Waiting on last week's export package",
    category: "privacy",
    priority: "normal",
    status: "waiting",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "portal",
    tags: ["export"],
    hoursAgo: 96,
    slaHours: 8,
    unread: false,
    firstResponseHoursAgo: 90,
    messages: [
      {
        authorType: "customer",
        authorName: "Nina Volkov",
        minutesAgo: 5760,
        channel: "portal",
        body: "Has the data export for Silveroak gone to our recovery email yet? We requested it six days ago after verification.",
      },
      {
        authorType: "operator",
        authorName: "Elena Voss",
        minutesAgo: 5400,
        channel: "portal",
        body: "The export SLA is seven calendar days from verification. Privacy Operations still has this inside the window. I will update as soon as delivery is confirmed.",
      },
    ],
  },
  {
    id: "tkt_resolved_zapier",
    publicId: "TKT-2026-00117",
    customerId: "cus_samir_patel",
    subject: "Zapier 401 on /v1/projects",
    category: "integrations",
    priority: "normal",
    status: "resolved",
    assigneeId: "usr_aisha_rahman",
    channel: "chat",
    tags: ["zapier"],
    hoursAgo: 120,
    slaHours: 8,
    unread: false,
    firstResponseHoursAgo: 118,
    resolvedHoursAgo: 100,
    messages: [
      {
        authorType: "customer",
        authorName: "Samir Patel",
        minutesAgo: 7200,
        channel: "chat",
        body: "Zapier cannot list projects. 401. We have not used the OAuth app in months.",
      },
      {
        authorType: "operator",
        authorName: "Aisha Rahman",
        minutesAgo: 7080,
        channel: "chat",
        body: "Refresh tokens expire after 90 days of inactivity. Reconnect the app from Settings > Developer. I will not paste a personal access token into chat.",
      },
    ],
  },
  {
    id: "tkt_escalated_credit",
    publicId: "TKT-2026-00118",
    customerId: "cus_greta_holm",
    subject: "Need a $4,800 goodwill credit",
    category: "billing",
    priority: "high",
    status: "escalated",
    assigneeId: "usr_marcus_pell",
    channel: "email",
    tags: ["credit", "enterprise"],
    hoursAgo: 26,
    slaHours: 4,
    unread: false,
    firstResponseHoursAgo: 24,
    messages: [
      {
        authorType: "customer",
        authorName: "Greta Holm",
        minutesAgo: 1560,
        channel: "email",
        body: "Fjordbank wants an $4,800 credit for last quarter's incident. Please apply it to the enterprise annual invoice today.",
      },
      {
        authorType: "operator",
        authorName: "Marcus Pell",
        minutesAgo: 1440,
        channel: "email",
        body: "Credits over $1,000 and enterprise annual write-offs require billing lead approval. I escalated rather than promising the amount in this thread.",
      },
    ],
  },
  {
    id: "tkt_rate_limit",
    publicId: "TKT-2026-00119",
    customerId: "cus_felix_nguyen",
    subject: "Hitting 429s on the Business plan",
    category: "integrations",
    priority: "normal",
    status: "new",
    assigneeId: null,
    channel: "portal",
    tags: ["rate-limit"],
    hoursAgo: 3.5,
    slaHours: 8,
    unread: true,
    messages: [
      {
        authorType: "customer",
        authorName: "Felix Nguyen",
        minutesAgo: 210,
        channel: "portal",
        body: "Our jobs get 429 from the API. Business plan. Can you raise the limit from this ticket?",
      },
    ],
  },
  {
    id: "tkt_archive_cards",
    publicId: "TKT-2026-00120",
    customerId: "cus_tara_quinn",
    subject: "How long after cancel is data kept?",
    category: "cancellation",
    priority: "normal",
    status: "resolved",
    assigneeId: DEMO_OPERATOR_ID,
    channel: "email",
    tags: ["retention"],
    hoursAgo: 200,
    slaHours: 8,
    unread: false,
    firstResponseHoursAgo: 196,
    resolvedHoursAgo: 180,
    messages: [
      {
        authorType: "customer",
        authorName: "Tara Quinn",
        minutesAgo: 12000,
        channel: "email",
        body: "If we cancel, how long do you keep the workspace before deletion?",
      },
      {
        authorType: "operator",
        authorName: "Elena Voss",
        minutesAgo: 11760,
        channel: "email",
        body: "Thirty days after the paid period ends the workspace is marked for deletion unless you reactivate. Request exports before the period ends.",
      },
    ],
  },
];
