"""Fictional operators, customers, and demo login accounts."""

from __future__ import annotations

DEMO_WORKSPACE_ID = "ws_heliodesk_demo"
DEMO_OPERATOR_ID = "usr_elena_voss"

OPERATORS = [
    {
        "id": DEMO_OPERATOR_ID,
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Elena Voss",
        "email": "elena.voss@heliodesk.example",
        "role": "admin",
        "title": "Support lead",
    },
    {
        "id": "usr_marcus_pell",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Marcus Pell",
        "email": "marcus.pell@heliodesk.example",
        "role": "operator",
        "title": "Billing specialist",
    },
    {
        "id": "usr_aisha_rahman",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Aisha Rahman",
        "email": "aisha.rahman@heliodesk.example",
        "role": "operator",
        "title": "Trust & Safety",
    },
]

CUSTOMERS = [
    {
        "id": "cus_jordan_hale",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Jordan Hale",
        "email": "jordan.hale@northpark.example",
        "company": "Northpark Analytics",
        "plan": "Business Annual",
        "region": "US-East",
        "created_at": "2024-11-02T10:00:00.000Z",
        "account_id": "acc_9f2c18",
        "health": "watch",
    },
    {
        "id": "cus_naomi_brooks",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Naomi Brooks",
        "email": "naomi.brooks@fieldline.example",
        "company": "Fieldline Studio",
        "plan": "Business Monthly",
        "region": "US-West",
        "created_at": "2025-02-14T10:00:00.000Z",
        "account_id": "acc_44ab01",
        "health": "good",
    },
    {
        "id": "cus_theo_marin",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Theo Marin",
        "email": "theo.marin@lumenyard.example",
        "company": "Lumenyard Co",
        "plan": "Enterprise",
        "region": "EU-West",
        "created_at": "2023-08-21T10:00:00.000Z",
        "account_id": "acc_77ce12",
        "health": "risk",
    },
    {
        "id": "cus_priya_sen",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Priya Sen",
        "email": "priya.sen@harborwell.example",
        "company": "Harborwell Health",
        "plan": "Enterprise",
        "region": "US-East",
        "created_at": "2024-04-03T10:00:00.000Z",
        "account_id": "acc_12dd90",
        "health": "good",
    },
    {
        "id": "cus_luis_ortega",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Luis Ortega",
        "email": "luis.ortega@stackmill.example",
        "company": "Stackmill",
        "plan": "Business Annual",
        "region": "US-Central",
        "created_at": "2025-01-09T10:00:00.000Z",
        "account_id": "acc_55ee33",
        "health": "watch",
    },
    {
        "id": "cus_hannah_cho",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Hannah Cho",
        "email": "hannah.cho@paperkite.example",
        "company": "Paperkite",
        "plan": "Starter",
        "region": "APAC",
        "created_at": "2025-06-18T10:00:00.000Z",
        "account_id": "acc_88aa21",
        "health": "good",
    },
    {
        "id": "cus_owen_blake",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Owen Blake",
        "email": "owen.blake@ridgeandco.example",
        "company": "Ridge & Co",
        "plan": "Business Annual",
        "region": "UK",
        "created_at": "2024-09-11T10:00:00.000Z",
        "account_id": "acc_21bb09",
        "health": "good",
    },
    {
        "id": "cus_sofia_lindgren",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Sofia Lindgren",
        "email": "sofia.lindgren@unknown.example",
        "company": "Unknown requester",
        "plan": "Enterprise",
        "region": "EU-North",
        "created_at": "2025-12-01T10:00:00.000Z",
        "account_id": "acc_03cc77",
        "health": "risk",
    },
    {
        "id": "cus_malik_adeyemi",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Malik Adeyemi",
        "email": "malik.adeyemi@brightlane.example",
        "company": "Brightlane Logistics",
        "plan": "Enterprise",
        "region": "US-East",
        "created_at": "2023-03-15T10:00:00.000Z",
        "account_id": "acc_90ff02",
        "health": "watch",
    },
    {
        "id": "cus_claire_dubois",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Claire Dubois",
        "email": "claire.dubois@ateliernord.example",
        "company": "Atelier Nord",
        "plan": "Business Monthly",
        "region": "EU-West",
        "created_at": "2025-05-02T10:00:00.000Z",
        "account_id": "acc_66aa18",
        "health": "good",
    },
    {
        "id": "cus_ren_takahashi",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Ren Takahashi",
        "email": "ren.takahashi@kintsugi.example",
        "company": "Kintsugi Labs",
        "plan": "Business Annual",
        "region": "APAC",
        "created_at": "2024-07-22T10:00:00.000Z",
        "account_id": "acc_14de55",
        "health": "good",
    },
    {
        "id": "cus_vic_moreau",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Vic Moreau",
        "email": "vic.moreau@copperline.example",
        "company": "Copperline Media",
        "plan": "Business Annual",
        "region": "US-West",
        "created_at": "2024-01-19T10:00:00.000Z",
        "account_id": "acc_72cc01",
        "health": "risk",
    },
    {
        "id": "cus_amira_hassan",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Amira Hassan",
        "email": "amira.hassan@civicspan.example",
        "company": "CivicSpan",
        "plan": "Enterprise",
        "region": "US-East",
        "created_at": "2025-03-08T10:00:00.000Z",
        "account_id": "acc_29ab70",
        "health": "watch",
    },
    {
        "id": "cus_ben_park",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Ben Park",
        "email": "ben.park@nimbusrail.example",
        "company": "Nimbus Rail",
        "plan": "Business Annual",
        "region": "US-East",
        "created_at": "2024-10-30T10:00:00.000Z",
        "account_id": "acc_81ee44",
        "health": "good",
    },
    {
        "id": "cus_nina_volkov",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Nina Volkov",
        "email": "nina.volkov@silveroak.example",
        "company": "Silveroak Research",
        "plan": "Enterprise",
        "region": "EU-East",
        "created_at": "2023-12-12T10:00:00.000Z",
        "account_id": "acc_05aa99",
        "health": "good",
    },
    {
        "id": "cus_samir_patel",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Samir Patel",
        "email": "samir.patel@wellthread.example",
        "company": "Wellthread",
        "plan": "Starter",
        "region": "US-West",
        "created_at": "2025-08-01T10:00:00.000Z",
        "account_id": "acc_38dd12",
        "health": "good",
    },
    {
        "id": "cus_greta_holm",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Greta Holm",
        "email": "greta.holm@fjordbank.example",
        "company": "Fjordbank Labs",
        "plan": "Enterprise",
        "region": "EU-North",
        "created_at": "2024-05-16T10:00:00.000Z",
        "account_id": "acc_61cc08",
        "health": "watch",
    },
    {
        "id": "cus_felix_nguyen",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Felix Nguyen",
        "email": "felix.nguyen@orbitworks.example",
        "company": "Orbitworks",
        "plan": "Business Monthly",
        "region": "APAC",
        "created_at": "2025-04-27T10:00:00.000Z",
        "account_id": "acc_47bb23",
        "health": "good",
    },
    {
        "id": "cus_tara_quinn",
        "workspace_id": DEMO_WORKSPACE_ID,
        "name": "Tara Quinn",
        "email": "tara.quinn@maplecroft.example",
        "company": "Maplecroft Design",
        "plan": "Business Annual",
        "region": "US-East",
        "created_at": "2024-08-09T10:00:00.000Z",
        "account_id": "acc_19ee71",
        "health": "good",
    },
]
