/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppArchitectureRouteImport } from './routes/_app/architecture'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox.index'
import { Route as AppInboxTicketIdRouteImport } from './routes/_app/inbox.$ticketId'
import { Route as AppKnowledgeIndexRouteImport } from './routes/_app/knowledge.index'
import { Route as AppKnowledgeDocumentIdRouteImport } from './routes/_app/knowledge.$documentId'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1TicketsRouteImport } from './routes/api/v1/tickets'
import { Route as ApiV1DemoResetRouteImport } from './routes/api/v1/demo.reset'
import { Route as ApiV1TicketsTicketIdRouteImport } from './routes/api/v1/tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppInboxTicketIdRoute = AppInboxTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppKnowledgeIndexRoute = AppKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKnowledgeRoute,
} as any)
const AppKnowledgeDocumentIdRoute = AppKnowledgeDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppKnowledgeRoute,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsRoute = ApiV1TicketsRouteImport.update({
  id: '/api/v1/tickets',
  path: '/api/v1/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DemoResetRoute = ApiV1DemoResetRouteImport.update({
  id: '/api/v1/demo/reset',
  path: '/api/v1/demo/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsTicketIdRoute = ApiV1TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => ApiV1TicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/architecture': typeof AppArchitectureRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/knowledge': typeof AppKnowledgeRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/inbox/$ticketId': typeof AppInboxTicketIdRoute
  '/knowledge/$documentId': typeof AppKnowledgeDocumentIdRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/tickets': typeof ApiV1TicketsRouteWithChildren
  '/inbox/': typeof AppInboxIndexRoute
  '/knowledge/': typeof AppKnowledgeIndexRoute
  '/api/v1/demo/reset': typeof ApiV1DemoResetRoute
  '/api/v1/tickets/$ticketId': typeof ApiV1TicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/architecture': typeof AppArchitectureRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/inbox/$ticketId': typeof AppInboxTicketIdRoute
  '/knowledge/$documentId': typeof AppKnowledgeDocumentIdRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/tickets': typeof ApiV1TicketsRouteWithChildren
  '/inbox': typeof AppInboxIndexRoute
  '/knowledge': typeof AppKnowledgeIndexRoute
  '/api/v1/demo/reset': typeof ApiV1DemoResetRoute
  '/api/v1/tickets/$ticketId': typeof ApiV1TicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/architecture': typeof AppArchitectureRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/knowledge': typeof AppKnowledgeRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/inbox/$ticketId': typeof AppInboxTicketIdRoute
  '/_app/knowledge/$documentId': typeof AppKnowledgeDocumentIdRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/tickets': typeof ApiV1TicketsRouteWithChildren
  '/_app/inbox/': typeof AppInboxIndexRoute
  '/_app/knowledge/': typeof AppKnowledgeIndexRoute
  '/api/v1/demo/reset': typeof ApiV1DemoResetRoute
  '/api/v1/tickets/$ticketId': typeof ApiV1TicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/architecture'
    | '/dashboard'
    | '/inbox'
    | '/knowledge'
    | '/settings'
    | '/api/health'
    | '/inbox/$ticketId'
    | '/knowledge/$documentId'
    | '/api/v1/health'
    | '/api/v1/tickets'
    | '/inbox/'
    | '/knowledge/'
    | '/api/v1/demo/reset'
    | '/api/v1/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/architecture'
    | '/dashboard'
    | '/settings'
    | '/api/health'
    | '/inbox/$ticketId'
    | '/knowledge/$documentId'
    | '/api/v1/health'
    | '/api/v1/tickets'
    | '/inbox'
    | '/knowledge'
    | '/api/v1/demo/reset'
    | '/api/v1/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analytics'
    | '/_app/architecture'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/_app/knowledge'
    | '/_app/settings'
    | '/api/health'
    | '/_app/inbox/$ticketId'
    | '/_app/knowledge/$documentId'
    | '/api/v1/health'
    | '/api/v1/tickets'
    | '/_app/inbox/'
    | '/_app/knowledge/'
    | '/api/v1/demo/reset'
    | '/api/v1/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1TicketsRoute: typeof ApiV1TicketsRouteWithChildren
  ApiV1DemoResetRoute: typeof ApiV1DemoResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/architecture': {
      id: '/_app/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/inbox/$ticketId': {
      id: '/_app/inbox/$ticketId'
      path: '/$ticketId'
      fullPath: '/inbox/$ticketId'
      preLoaderRoute: typeof AppInboxTicketIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/knowledge/': {
      id: '/_app/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AppKnowledgeIndexRouteImport
      parentRoute: typeof AppKnowledgeRoute
    }
    '/_app/knowledge/$documentId': {
      id: '/_app/knowledge/$documentId'
      path: '/$documentId'
      fullPath: '/knowledge/$documentId'
      preLoaderRoute: typeof AppKnowledgeDocumentIdRouteImport
      parentRoute: typeof AppKnowledgeRoute
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets': {
      id: '/api/v1/tickets'
      path: '/api/v1/tickets'
      fullPath: '/api/v1/tickets'
      preLoaderRoute: typeof ApiV1TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/demo/reset': {
      id: '/api/v1/demo/reset'
      path: '/api/v1/demo/reset'
      fullPath: '/api/v1/demo/reset'
      preLoaderRoute: typeof ApiV1DemoResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/$ticketId': {
      id: '/api/v1/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/api/v1/tickets/$ticketId'
      preLoaderRoute: typeof ApiV1TicketsTicketIdRouteImport
      parentRoute: typeof ApiV1TicketsRoute
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxTicketIdRoute: typeof AppInboxTicketIdRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxTicketIdRoute: AppInboxTicketIdRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppKnowledgeRouteChildren {
  AppKnowledgeDocumentIdRoute: typeof AppKnowledgeDocumentIdRoute
  AppKnowledgeIndexRoute: typeof AppKnowledgeIndexRoute
}

const AppKnowledgeRouteChildren: AppKnowledgeRouteChildren = {
  AppKnowledgeDocumentIdRoute: AppKnowledgeDocumentIdRoute,
  AppKnowledgeIndexRoute: AppKnowledgeIndexRoute,
}

const AppKnowledgeRouteWithChildren = AppKnowledgeRoute._addFileChildren(
  AppKnowledgeRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppKnowledgeRoute: typeof AppKnowledgeRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppArchitectureRoute: AppArchitectureRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppKnowledgeRoute: AppKnowledgeRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1TicketsRouteChildren {
  ApiV1TicketsTicketIdRoute: typeof ApiV1TicketsTicketIdRoute
}

const ApiV1TicketsRouteChildren: ApiV1TicketsRouteChildren = {
  ApiV1TicketsTicketIdRoute: ApiV1TicketsTicketIdRoute,
}

const ApiV1TicketsRouteWithChildren = ApiV1TicketsRoute._addFileChildren(
  ApiV1TicketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1TicketsRoute: ApiV1TicketsRouteWithChildren,
  ApiV1DemoResetRoute: ApiV1DemoResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
